services:
  - type: web
    name: ovaview-scraper
    runtime: python
    pythonVersion: 3.13
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --timeout 300 api_server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.13
      - key: FLASK_ENV
        value: production
      - key: PORT
        value: 5000
